### ISSUE TITLE
Budget logic analyzer

### ISSUE THREAD

**Issue by tf131** [peterhinch/micropython-monitor#1]
Hi Peter,
First of all, I would like to thank you for the great project. Since the price range is enormous (10-1000 €) I wanted to ask for a recommendation for a useful (low) budget logic analyzer for monitoring ESP32 applications.
Many thanks in advance!
Tim

**Comment by peterhinch** [comment]
About a year ago I bought a Saleae clone for under 10€. This works fine, but only with old Saleae firmware. Its big failure is that it can't capture pr-trigger data, so I replaced it with an 8 channel Saleae. This is brilliant, but expensive. I haven't tried any others, but I do recommend getting one that can record pre-trigger data. This is crucial as you usually need to know what was going on prior to an event like CPU hogging, so that you can figure out the cause. One that can decode protocols such as UART data, I2C, SPI and suchlike is very useful (Saleae can do all of that). Jim Mussared (@jimmo) has a DSLogic: these are cheaper than Saleae and might be worth investigating.

A proper LA is definitely best, but for the one purpose of monitoring MicroPython code there is also my [analyser](https://github.com/peterhinch/micropython-monitor/blob/master/ANALYSER.md) back-end. However I get the feeling that most people with a need for monitoring are already equipped with a LA. Unless there is a definite interest I'll probably abandon this.
